### ISSUE TITLE
10/30 Lab Sign-Off

### ISSUE THREAD

**Issue by evhaase** [evhaase/C313_JCWSoilAnalysis#1]
I worked on two RMDs to attempt to merge the AA data and the sample key data. Find these files in the file R -> 02_DataTidyingAA or 03_DataTidyingAA_Success. File 02_DataTidyingAA involved editing the way the columns were set up, often from having characters to being numerical, before/while importing the data. This was then merged and an issue of multiple readings at sample 10 which was not desirable. To fix this, Gillian guided me in changing the columns after the data sets had been imported. This eliminated the issue of having multiple samples with the same value. This edited and successful RMD file is named 03_DataTidyingAA_Success.

**Comment by vestoj** [comment]
Nice work, your code looks good! I couldn't find the final tidy datasets, were you able to save them as .csv files?
